Controllers/LogInController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using WebWordGame.Models;

namespace WebWordGame.Controllers
{
    public class LogInController : Controller
    {
        private readonly DataBaseContext _dataBaseContext;



        public LogInController(DataBaseContext dataBaseContext)
        {

            _dataBaseContext = dataBaseContext;
        }


        //Методы для регистрации
        [HttpGet]
        public IActionResult Registration()
        {
            if (User.Identity.IsAuthenticated)
            {
                return RedirectToAction("index", "home");
            }
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Registration(RegistrationModel model)
        {
            if (ModelState.IsValid)
            {
                PersonModel person = await _dataBaseContext.People.FirstOrDefaultAsync(u => u.LoginName == model.LoginName);
                PersonModel personEmail = await _dataBaseContext.People.FirstOrDefaultAsync(u => u.Email == model.Email);
                if (person == null && personEmail == null)
                {
                    // добавляем пользователя в бд
                    person = new PersonModel { LoginName = model.LoginName, Email = model.Email, Password = Crypto.Hash(model.Password) };
                    Role userRole = await _dataBaseContext.Roles.FirstOrDefaultAsync(r => r.Name == "person");
                    if (userRole != null)
                        person.Role = userRole;

                    GameInfoModel quantityOfPeople = _dataBaseContext.GameInfo.First();
                    quantityOfPeople.QuantityOfPlayers += 1;

                    ImageModel userImage = await _dataBaseContext.Images.FirstOrDefaultAsync(i => i.ImageSource == "../images/starting_profile_images/default_image.jpg");
                    person.ProfileImageId = userImage;
                    person.QuantityOfWins = 0;
                    _dataBaseContext.People.Add(person);
                    await _dataBaseContext.SaveChangesAsync();

                    await Authenticate(person); // аутентификация

                    return RedirectToAction("index", "home");
                }
                else
                {
                    if (person != null)
                    {
                        ModelState.AddModelError("", "Пользователь с таким логином уже зарегистрирован!");

                    }
                    if (personEmail != null)
                    {
                        ModelState.AddModelError("", "Пользователь с такой почтой уже зарегистрирован!");

                    }
                }
            }
            return View(model);
        }



        //Методы для входа 

        [HttpGet]

        public IActionResult Login()
        {
            if (User.Identity.IsAuthenticated )
            {
                return RedirectToAction("index", "home");
            }
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(LoginModel model)
        {
            if (ModelState.IsValid)
            {
                PersonModel person = await _dataBaseContext.People
                    .Include(u => u.Role)
                    .FirstOrDefaultAsync(u => u.LoginName == model.LoginName);
                if (person != null)
                {
                    bool IsVerifyPassword = Crypto.VerifyHashed(person.Password, model.Password);
                    if (IsVerifyPassword)
                    {
                        await Authenticate(person); // аутентификация

                        return RedirectToAction("index", "home");
                    }
                }
                

                ModelState.AddModelError("", "Некорректные логин и(или) пароль");
            }
            return View(model);
        }


        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync();
            return RedirectToAction("index","home");
        }







        private async Task Authenticate(PersonModel person)
        {
            // создаем один claim
            var claims = new List<Claim>
            {
                new Claim(ClaimsIdentity.DefaultNameClaimType, person.LoginName),
                new Claim(ClaimsIdentity.DefaultRoleClaimType, person.Role?.Name)
            };
            // создаем объект ClaimsIdentity
            ClaimsIdentity id = new ClaimsIdentity(claims, "ApplicationCookie", ClaimsIdentity.DefaultNameClaimType,
                ClaimsIdentity.DefaultRoleClaimType);
            // установка аутентификационных куки
            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(id));
        }
    }


}

Views/LogIn/Index.cshtml
@model WebWordGame.Models.PersonModel

<div>
    <div id="main">
        <div id="logInForm">
            <div id="registration">

                <form asp-action="Create" name="registrationForm">
                    <div style="text-align: center; text-decoration: underline;">
                        Зарегистрируйся и играй
                    </div>


                    @Html.LabelFor(model => model.LoginName)
                    <br />
                    @Html.EditorFor(model => model.LoginName)
                    <br />
                    @Html.LabelFor(model => model.Email)
                    <br />
                    @Html.EditorFor(model => model.Email)
                    <br />
                    @Html.LabelFor(model => model.Password)
                    <br />
                    @Html.EditorFor(model => model.Password)
                    <br />
                    Повтор пароля
                    <br />
                    ??????????????
                    <br />

                    <input class="menuBtns" type="submit" value="Зарегистрироваться" />
                    <input class="menuBtns" type="button" value="Уже есть аккаунт?" onclick="showLoginMenu(true)" />
                    <input class="menuBtns" type="button" value="В главное меню" onclick="" />

                </form>

            </div>

            <div id="login" style="display: none;">

                <form asp-action="" name="registrationForm">
                    <div style="text-align: center; text-decoration: underline;">
                        Войди и играй
                    </div>


                    @Html.LabelFor(model => model.LoginName)
                    <br />
                    @Html.EditorFor(model => model.LoginName)

                    <br />
                    @Html.LabelFor(model => model.Password)
                    <br />
                    @Html.EditorFor(model => model.Password)


                    <input class="menuBtns" type="submit" value="Войти" />
                    <input class="menuBtns" type="button" value="Нет аккаунта?" onclick="showLoginMenu(false)" />
                    <input class="menuBtns" type="button" value="В главное меню" onclick="" />



                </form>
            </div>


        </div>

    </div>
</div>

Views/LogIn/Login.cshtml
@model WebWordGame.Models.LoginModel
@{
    ViewBag.Title = "Вход";
}
<div>
    <div id="main">
        <div id="logInForm">

            <div id="login" style="display: inline;">


                <div style="text-align: center; text-decoration: underline;">
                    Войди и играй
                </div>
                <br />

                <form asp-action="Login" asp-controller="LogIn" asp-anti-forgery="true">
                    <div class="validation" asp-validation-summary="ModelOnly"></div>
                    <div>
                        <div class="form-group">
                            @*<label asp-for="LoginName">Введите логин</label>*@
                            <input type="text" asp-for="LoginName" class="inputBlock" placeholder="Введите логин" autocomplete="off" />
                            <span asp-validation-for="LoginName" class="attention-text" />
                        </div>
                        <br />
                        <div class="form-group">
                            @*<label asp-for="Password">Введите пароль</label>*@
                            <input asp-for="Password" class="inputBlock" placeholder="Введите пароль" autocomplete="off" />
                            <span asp-validation-for="Password" class="attention-text" />
                        </div>
                        <div id="hideAndSeekPasswordBlock" style="display: flex;">
                            <div id="forEyeBlock" style=" margin-top: auto; margin-bottom: auto;"></div>
                            <div id="TextForShowPass" style="font-size:19px;">Показать пароль</div>
                            <div id="TextForHidePass" style="display: none; font-size:19px;">Скрыть пароль</div>

                        </div>

                        <div class="formForBtns">
                            <input type="submit" value="Войти" class="menuBtns formBtns" />
                            <a class="menuBtns formBtns" asp-action="registration" asp-controller="login"> Нет аккаунта? </a>
                            <a class="menuBtns formBtns" asp-action="index" asp-controller="home"> В главное меню </a>

                        </div>
                    </div>
                </form>


            </div>


        </div>

    </div>
</div>

Views/LogIn/Registration.cshtml
@model WebWordGame.Models.RegistrationModel
@{
    ViewBag.Title = "Регистрация";
}

<div>
    <div id="main">
        <div id="logInForm">
            <div id="registration">



                <div style="text-align: center; text-decoration: underline;">
                    Зарегистрируйся и играй
                </div>
                <br />

                <form asp-action="Registration" asp-controller="LogIn" asp-anti-forgery="true">
                    <div class="validation" asp-validation-summary="ModelOnly"></div>

                    <div>
                        <div>
                            @*<label asp-for="LoginName">Введите Login</label><br />*@
                            <input type="text" asp-for="LoginName" class="inputBlock" placeholder="Введите логин" autocomplete="off" />
                            <span asp-validation-for="LoginName" class="attention-text" />
                        </div>
                        <br />

                        <div>
                            @*<label asp-for="Email">Введите Email</label><br />*@
                            <input type="text" asp-for="Email" class="inputBlock" placeholder="Введите почтовый адрес" autocomplete="off" />
                            <span asp-validation-for="Email" class="attention-text" />

                        </div>
                        <br />

                        <div>
                            @*<label asp-for="Password">Введите пароль</label><br />*@
                            <input asp-for="Password" class="inputBlock" placeholder="Введите пароль" autocomplete="off" />
                            <span asp-validation-for="Password" class="attention-text" />


                        </div>
                        <div id="hideAndSeekPasswordBlock" style="display: flex;">
                            <div id="forEyeBlock" style=" margin-top: auto; margin-bottom: auto;"></div>
                            <div id="TextForShowPass" style="font-size:19px;">Показать пароль</div>
                            <div id="TextForHidePass" style="display: none; font-size:19px;">Скрыть пароль</div>

                        </div>
                        <div>
                            @*<label asp-for="ConfirmPassword">Повторите пароль</label><br />*@
                            <input asp-for="ConfirmPassword" class="inputBlock" placeholder="Повторите пароль" autocomplete="off" />
                            <span asp-validation-for="ConfirmPassword" class="attention-text" />
                        </div>
                        @*<div>
                                <input type="submit" value="Регистрация" />
                            </div>*@
                        <div class="formForBtns">
                            <input class="menuBtns formBtns" type="submit" value="Зарегистрироваться" />
                            <br />
                            <a class="menuBtns formBtns" asp-action="login" asp-controller="login"> Уже есть аккаунт? </a>
                            <br />
                            <a class="menuBtns formBtns" asp-action="index" asp-controller="home"> В главное меню </a>

                        </div>
                    </div>
                </form>
            </div>


        </div>

    </div>
</div>